### ISSUE TITLE
Ban and warn commands do not appear to work

### ISSUE THREAD

**Issue by JosTheDude** [DarkShadow19/Guild-Bot#1]
I've setup MongoDB correctly and the !rep command works but whenever I do !ban [ign / uuid] it doesnt seem to update the Mongo entry nor do anything at all. This is the same for !warn set [ign] 1 

Yet !warns [ign] still works if I update the value in MongoDB compass

**Comment by MX1D** [comment]
idk why i didn't get notified about this ty github but im working on a rewrite version of it to fix everything and re code the entire bot the current code is too messy

**Comment by MX1D** [comment]
reopened cuz i found that for some reason first time u run the command bot doesn't reply which is being fixed in the rewrite version
