### ISSUE TITLE
Hypixel Support for the version the bot is using may be ending

### ISSUE THREAD

**Issue by JosTheDude** [DarkShadow19/Guild-Bot#7]
When I start up my bot using PM2, hypixel sends my bot a message saying "WARNING: Hypixel Server support for the version of Minecraft that you are using may be ending in the near future.
We would recommend using version 1.8 or the most recent version of Minecraft."

**Comment by MX1D** [comment]
The rewrite is already out + V3 is work in progress I would recommend updating to the rewrite or waiting until V3 is out
